### ISSUE TITLE
Cannot set border property for focused input element

### ISSUE THREAD

**Issue by nyszilard** [code-farmz/ng-otp-input#110]
I would like to set the border property of the focused input element, but it doesn't work:
``` css
:host ::ng-deep .otp-input:focus {
  border-color: red !important;
}
```
